mutation addSimpleCart ($cart_id: String!, $quantity: Float!, $sku: String!) {
    addSimpleProductsToCart(
        input: {
            cart_id: $cart_id, 
            cart_items: {
                data: { 
                    quantity: $quantity, 
                    sku: $sku 
                }
            }
        }
    ) {
        cart {
            items {
                id
                product {
                    name
                    sku
                }
                quantity
            }
        }
    }
}