mutation paymentMethods($cart_id: String!, $code: String!, $purchase_order_number: String) {
    setPaymentMethodOnCart (
        input: {
            cart_id: $cart_id,
            payment_method: {
                code: $code
                purchase_order_number: $purchase_order_number
            }
        }
    ){
        cart {
            email
            items {
                id
                product {
                    id
                    name
                    sku
                    type_id
                    image {
                        label
                        url
                    }
                    price {
                        maximalPrice {
                            amount {
                                currency
                                value        
                            }
                        }
                        minimalPrice {
                            amount {
                                currency
                                value        
                            }
                        }
                        regularPrice {
                            amount {
                                currency
                                value        
                            }
                        }
                    }
                    swatch_image
                    special_price
                    tier_price
                    stock_status
                    new_from_date
                    new_to_date
                    special_from_date
                    special_to_date
                    created_at
                    updated_at
                }
                quantity
            }
            prices {
                applied_taxes {
                    amount {
                        currency
                        value
                    }
                    label
                }
                grand_total {
                    currency
                    value
                }
                subtotal_excluding_tax {
                    currency
                    value
                }
                subtotal_including_tax {
                    currency
                    value
                }
                subtotal_with_discount_excluding_tax {
                    currency
                    value
                }
            }
            applied_coupon {
                code
            }
            available_payment_methods {
                code
                title
            }
            shipping_addresses {
                cart_items {
                    cart_item_id
                    quantity
                }
                city
                company
                country {
                    code
                    label
                }
                customer_notes
                firstname
                items_weight
                lastname
                postcode
                region {
                    code
                    label
                }
                street
                telephone
                available_shipping_methods {
                    available
                    carrier_code
                    carrier_title
                    error_message
                    method_code
                    method_title
                    amount {
                        currency
                        value
                    }
                    base_amount {
                        currency
                        value
                    }
                    price_excl_tax {
                        currency
                        value
                    }
                    price_incl_tax {
                        currency
                        value
                    }
                }
                selected_shipping_method {
                    carrier_code
                    carrier_title
                    method_code
                    method_title
                    amount {
                        currency
                        value
                    }
                    base_amount {
                        currency
                        value
                    }
                }
            }
            billing_address {
                city
                company
                country {
                    code
                    label
                }
                customer_notes
                firstname
                lastname
                postcode
                region {
                    code
                    label
                }
                street
                telephone
            }
            available_payment_methods {
                code
                title
            }
            selected_payment_method {
                code
                purchase_order_number
                title
            }
        }
    }
}