<?php
/**
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
?>
<v-product-details inline-template>
    <?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
        <v-tabs class="in-details">
            <?php $layout = $block->getLayout(); ?>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <v-tabs-panel label="<?= $label ?>">
                    <?= $html ?>
                </v-tabs-panel>
            <?php endforeach;?>
        </v-tabs>
    <?php endif; ?>
</v-product-details>