<?php
/** @var \Magento\Customer\Block\Form\Login $block */
?>

<div class="block in-login">
    <v-lazy-component>
        <v-login-form inline-template>
            <div class="block-login">
                <div class="block-title">
                    <strong v-text="i18n.title"></strong>
                </div>
                <div class="block-content">
                    <v-form ref="loginForm" method="post">
                        <v-form-item :label="i18n.email">
                            <v-input type="email" name="login[username]" rules="required|email" v-model="email"></v-input>
                        </v-form-item>
                        <v-form-item :label="i18n.password" :classes="'in-relative'">
                            <v-input type="password" name="login[password]" rules="required|alpha_num|min:6" :show="showEye" v-model="password"></v-input>
                        </v-form-item>
                        <v-form-item :classes="'in-flex'">
                            <v-button type="primary" native="button" v-text="i18n.signIn" @click="_login"></v-button>
                            <v-button type="link" :href="forgot_url" v-text="i18n.forgot"></v-button>
                        </v-form-item>
                    </v-form>
                </div>
                <v-modal :visible.sync="visible">
                    <template v-if="visible">
                        <p v-text="modalMsg"></p>
                    </template>
                </v-modal>
            </div>
        </v-login-form>
        <v-skeleton slot="skeleton">
            <v-skeleton-text :lines="8"></v-skeleton-text>
        </v-skeleton>
    </v-lazy-component>
</div>