<?php
/** @var \Magento\Customer\Block\Form\Register $block */
?>

<?= $block->getChildHtml('form_fields_before') ?>
<?= $block->getChildHtml('customer.form.register.extra') ?>

<v-create inline-template>
    <v-form class="v-account" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" enctype="multipart/form-data" method="post">
        <?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
        <?php endif ?>
        <v-form-item :label="i18n.email">
            <?= $block->getBlockHtml('formkey') ?>
            <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>" />
            <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>" />
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
            <input type="hidden" name="create_address" value="1" />
            <v-input type="email" name="email" v-model="email"></v-input>
        </v-form-item>
        <v-form-item :label="i18n.password">
            <v-input type="password" name="password" :show="showEye" v-model="password"></v-input>
        </v-form-item>
        <v-form-item :label="i18n.comfirm">
            <v-input type="password" name="password_confirmation" :show="showEye" v-model="comfirm"></v-input>
        </v-form-item>
        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <v-form-item class="v-country" :label="i18n.country">
            <v-select name="country_id" placeholder="Choose Country" :options="country" v-model="selectCountry" :filterable=true :icon=true :number=8 @change="changeRegion"></v-select>
        </v-form-item>
        <v-form-item :label="i18n.state">
            <v-input name="region" v-if="!showRegion" v-model="selectRegion"></v-input>
            <v-select name="region_id" v-if="showRegion" placeholder="Choose Region" :options="region" v-model="selectRegion" :filterable=true :number=8></v-select>
        </v-form-item>
        <v-form-item :label="i18n.city">
            <v-input name="city" v-model="city"></v-input>
        </v-form-item>
        <v-form-item :label="i18n.street">
            <v-input name="street[]" v-model="street[0]"></v-input>
            <template v-if="address_count > 0">
                <v-input name="street[]" class="v-form-address" v-for="item in counter" :key="item" v-model="street[item + 1]"></v-input>
            </template>
        </v-form-item>
        <?php $_company = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Company') ?>
        <?php if ($_company->isEnabled()): ?>
            <?= $_company->setCompany($block->getFormData()->getCompany())->toHtml() ?>
        <?php endif ?>
        <?php $_fax = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Fax') ?>
        <?php if ($_fax->isEnabled()): ?>
            <?= $_fax->setFax($block->getFormData()->getFax())->toHtml() ?>
        <?php endif ?>
        <v-form-item :label="i18n.zip">
            <v-input name="postcode" v-model="postcode"></v-input>
        </v-form-item>
        <?php $_telephone = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Telephone') ?>
        <?php if ($_telephone->isEnabled()): ?>
            <?= $_telephone->setTelephone($block->getFormData()->getTelephone())->toHtml() ?>
        <?php endif ?>
        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <?= $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
        <?php if ($addressAttributes): ?>
            <?php $addressAttributes->setEntityType('customer_address'); ?>
            <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
            <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
            <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
        <?php endif;?>
        <?= $block->getChildHtml('form_additional_info') ?>
        <?php if ($block->isNewsletterEnabled()): ?>
            <v-form-item>
                <v-checkbox name="is_subscribed" v-model="subscribed" value="1">{{i18n.subscribed}}</v-checkbox>
            </v-form-item>
            <?= $block->getChildHtml('customer.form.register.newsletter') ?>
        <?php endif ?>
        <v-form-item>
            <v-button type="primary" native="submit" v-text="i18n.button"></v-button>
        </v-form-item>
    </v-form>
</v-create>