<?php
/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>

<v-logo inline-template>
    <a class="logo" title="<?= /* @escapeNotVerified */ $storeName ?>">
        <img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
            title="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
            alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
            <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
            <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />
    </a>
</v-logo>