<?php
/** @var \Magento\Newsletter\Block\Subscribe $block */
?>

<v-newsletter inline-template>
    <div class="block newsletter">
        <v-form action="<?= $block->getFormActionUrl()?>" method="post">
            <v-form-item>
                <v-input type="email" name="email" v-model="email" v-bind:placeholder="i18n.emailAddress"></v-input>
                <v-button type="primary" native="submit" v-text="i18n.subscribe"></v-button>
            </v-form-item>
        </v-form>
    </div>
</v-newsletter>