<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>

<v-search inline-template>
    <div class="block block-search">
        <v-form class="form minisearch" action="<?= $helper->getResultUrl() ?>" method="get">
            <v-form-item>
                <v-input name="<?= $helper->getQueryParamName() ?>" v-model="search" maxlength="<?= $helper->getMaxQueryLength() ?>" :placeholder="i18n.search"></v-input>
            </v-form-item>
        </v-form>
    </div>
</v-search>