<?php
/**
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php 
    $_description = $block->getCurrentCategory()->getDescription();
?>

<v-category-description inline-template>
    <div class="category-description">
        <?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'description') ?>
    </div>
</v-category-description>
