<?php
/**  @var $block \Magento\Checkout\Block\Cart\Grid */
?>

<?= $block->getChildHtml('form_before') ?>
<v-shipping inline-template>
    <div class="in-shipping">
        <v-table :data="quoteItemData" :drag="true">
            <v-table-column :label="i18n.item">
                <template slot-scope="scope">
                    <a :href="filterUrl(scope.row)" :title="scope.row.name">
                        <img :src="scope.row.thumbnail" />
                    </a>
                    <p class="name" v-text="scope.row.name"></p>
                </template>
            </v-table-column>
            <v-table-column :label="i18n.price">
                <template slot-scope="scope">
                    <span v-text="priceFormat(scope.row.base_price_incl_tax)"></span>
                </template>
            </v-table-column>
            <v-table-column :label="i18n.qty" prop="qty"></v-table-column >
            <v-table-column :label="i18n.subtotal">
                <template slot-scope="scope">
                    <span v-text="priceFormat(scope.row.row_total_incl_tax)"></span>
                </template>
            </v-table-column>
            <v-table-column :label="i18n.operation">
                <template slot-scope="scope">
                    <a href="javascript:;" v-text="i18n.moveWishlist" @click="moveWishlist(scope.row)"></a>
                    <a href="javascript:;" v-text="i18n.remove" @click="removeItem(scope.row)"></a>
                </template>
            </v-table-column>
        </v-table>
    </div>
</v-shipping>

<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>