<v-gift inline-template>
    <div class="in-gift">
        <v-collapse>
            <v-collapse-panel name="gift">
                <h4 v-text="i18n.gift"></h4>
                <template slot="content">
                    <v-form-item>
                        <v-input name="gift_code" v-model="gift" :placeholder="i18n.gift"></v-input>
                    </v-form-item>
                    <v-form-item>
                        <v-button type="primary" native="button" v-text="i18n.applay"></v-button>
                    </v-form-item>
                </template>
            </v-collapse-panel>
        </v-collapse>
    </div>
</v-gift>