<?php
/*
* @var $block \Magento\Checkout\Block\Cart\Sidebar 
*/
?>

<v-minicart inline-template>
    <div class="minicart-wrapper">
        <a class="action showcart" href="<?= $block->getShoppingCartUrl() ?>" data-bind="scope: 'minicart_content'">
            <span class="counter qty empty">
                <span class="counter-number"></span>
            </span>
        </a>
        <?php if ($block->getIsNeedToDisplaySideBar()): ?>
            <div class="block block-minicart">
                <div class="minicart-content"></div>
                <?= $block->getChildHtml('minicart.addons') ?>
            </div>
        <?php endif ?>
    </div>
</v-minicart>