<?php
/**
 * @var \Magento\Directory\Block\Currency $block
 */
?>

<?php 
    $currencies = $block->getCurrencies();
    $currentCurrencyCode = $block->getCurrentCurrencyCode();
    $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '';
?>

<?php if ($block->getCurrencyCount() > 1): ?>
    <v-currency inline-template>
        <div class="switcher switcher-currency">
            <div class="actions dropdown  switcher-options">
                <div class="action toggle switcher-trigger"
                    id="switcher-currency-trigger<?= $block->escapeHtmlAttr($id) ?>"
                    data-mage-init='{"dropdown":{}}'
                    data-toggle="dropdown"
                    data-trigger-keypress-button="true">
                    <strong class="language-<?= $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
                        <span><?= $block->escapeHtml($currentCurrencyCode) ?> - <?= @$block->escapeHtml($currencies[$currentCurrencyCode]) ?></span>
                    </strong>
                </div>
                <ul class="dropdown switcher-dropdown" data-target="dropdown">
                    <?php foreach ($currencies as $_code => $_name): ?>
                        <?php if ($_code != $currentCurrencyCode): ?>
                            <li class="currency-<?= $block->escapeHtmlAttr($_code) ?> switcher-option">
                                <a href="#" data-post='<?= /* @noEscape */ $block->getSwitchCurrencyPostData($_code) ?>'><?= $block->escapeHtml($_code) ?> - <?= $block->escapeHtml($_name) ?></a>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </v-currency>
<?php endif; ?>