<?php
/**
 * @var $block \Magento\CatalogSearch\Block\Advanced\Form
 */
?>
<?php 
    $jsonHelper = \Magento\Framework\App\ObjectManager::getInstance()->create('Magento\Framework\Json\Helper\Data');
    $maxQueryLength = $this->helper('Magento\CatalogSearch\Helper\Data')->getMaxQueryLength();
?>

<v-advanced-form inline-template>
    <v-form class="in-advanced" action="<?= $block->getSearchPostUrl() ?>" method="get"> 
        <?php foreach ($block->getSearchableAttributes() as $_attribute): ?>
        <?php $_code = $_attribute->getAttributeCode() ?>
            <v-form-item label="<?= $block->getAttributeLabel($_attribute) ?>">
                <?php switch ($block->getAttributeInputType($_attribute)):
                    case 'number': ?>
                        <div class="in-line">
                            <v-input name="<?= $_code ?>[from]" v-model="<?= $_code . '_from' ?>" maxlength="<?= $maxQueryLength ?>" value="<?= $block->getAttributeValue($_attribute, 'from') ?>"></v-input>
                            <v-input name="<?= $_code ?>[to]" v-model="<?= $_code . '_to' ?>" maxlength="<?= $maxQueryLength ?>" value="<?= $block->getAttributeValue($_attribute, 'to') ?>"></v-input>
                        </div>
                    <?php break;
                    case 'price': ?>
                        <div class="in-line">
                            <v-input name="<?= $_code ?>[from]" v-model="<?= $_code . '_from' ?>" maxlength="<?= $maxQueryLength ?>" value="<?= $block->getAttributeValue($_attribute, 'from') ?>"></v-input>
                            <span>-</span>
                            <v-input name="<?= $_code ?>[to]" v-model="<?= $_code . '_to' ?>" maxlength="<?= $maxQueryLength ?>" value="<?= $block->getAttributeValue($_attribute, 'to') ?>"></v-input>
                            <span v-text="currency"></span>
                        </div>
                    <?php break;
                    case 'select': ?>
                        <v-select name="<?= $_attribute->getAttributeCode() ?>" :options="<?= $_attribute->getAttributeCode() ?>" v-model="selectColor" :filterable=true :multiple=true size="4"></v-select>
                    <?php break;
                    case 'yesno': ?>
                        <?= $block->getAttributeYesNoElement($_attribute) ?>
                    <?php break;
                    case 'date': ?>
                        <div class="in-flex">
                            <?= $block->getDateInput($_attribute, 'from') ?>
                            <?= $block->getDateInput($_attribute, 'to') ?>
                        </div>
                    <?php break;
                    default: ?>
                        <v-input name="<?= $_code ?>" v-model="<?= $_code ?>" maxlength="<?= $maxQueryLength ?>" value="<?= $block->getAttributeValue($_attribute) ?>"></v-input>
                <?php endswitch; ?>
            </v-form-item>
        <?php endforeach; ?>
        <v-form-item>
            <v-button type="primary" native="submit" v-text="i18n.search"></v-button>
        </v-form-item>
    </v-form>
</v-advanced-form>