<?php
/*
* @var \Magento\Contact\Block\ContactForm $block 
*/
?>

<v-contact-form inline-template>
    <v-form class="in-contact" action="<?= $block->getActionUrl() ?>" method="post"> 
        <v-form-item :label="i18n.name">
            <v-input name="name" v-model="name"></v-input>
        </v-form-item>
        <v-form-item :label="i18n.email">
            <v-input type="email" name="email" v-model="email"></v-input>
        </v-form-item>
        <v-form-item :label="i18n.telephone">
            <v-input type="number" name="telephone" v-model="telephone"></v-input>
        </v-form-item>
        <v-form-item :label="i18n.comment">
            <v-textarea name="comment" v-model="comment" :auto="auto"></v-textarea>
        </v-form-item>
        <v-form-item>
            <v-button type="primary" native="submit" v-text="i18n.submit"></v-button>
        </v-form-item>
    </v-form>
</v-contact-form>