<div class="price-box">
    <span class="special-price" v-if="!hasTier">
        <span class="price" v-text="priceFormat(finalPrice.amount)"></span>
    </span>
    <span class="tier-price" v-if="hasTier">
        <span class="price" v-text="priceFormat(tierPrice)"></span>
    </span>
    <span class="old-price" v-if="!hasSpecial">
        <span class="price" v-text="priceFormat(oldPrice.amount)"></span>
    </span>
</div>