<?php
/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
?>
<?php if ($title): ?>
    <v-title inline-template>
        <div class="page-title-wrapper">
            <h1 class="page-title">
                <?= /* @escapeNotVerified */ $title ?>
            </h1>
            <?= $block->getChildHtml() ?>
        </div>
    </v-title>
<?php endif; ?>