<v-discount inline-template>
    <div class="in-discount">
        <v-collapse>
            <v-collapse-panel name="discount">
                <h4 v-text="i18n.coupon"></h4>
                <template slot="content">
                    <v-form-item>
                        <v-input name="coupon_code" v-model="coupon" :placeholder="i18n.coupon"></v-input>
                    </v-form-item>
                    <v-form-item>
                        <v-button type="primary" native="button" v-text="i18n.applay"></v-button>
                    </v-form-item>
                </template>
            </v-collapse-panel>
        </v-collapse>
    </div>
</v-discount>