<v-guest-form inline-template>
    <v-form class="in-guest" action="<?= $block->getActionUrl() ?>" method="post"> 
        <v-form-item :label="i18n.orderId">
            <v-input name="oar_order_id" v-model="orderId"></v-input>
        </v-form-item>
        <v-form-item :label="i18n.billingName">
            <v-input name="oar_billing_lastname" v-model="billingName"></v-input>
        </v-form-item>
        <v-form-item :label="i18n.findOrder">
            <v-select name="oar_type" :options="type" v-model="selectType" :filterable=true></v-select>
        </v-form-item>
        <v-form-item :label="i18n.email">
            <v-input name="oar_email" v-model="email"></v-input>
        </v-form-item>
        <v-form-item :label="i18n.zip">
            <v-input name="oar_zip" v-model="zip"></v-input>
        </v-form-item>
        <v-form-item>
            <v-button type="primary" native="submit" v-text="i18n.continue"></v-button>
        </v-form-item>
    </v-form>
</v-guest-form>

<script src="<?= $block->getViewFileUrl('js/sales_guest.bundle.js') ?>" async="true"></script>