<?php
/*
* @var $block \Magento\Catalog\Block\Product\View 
*/
?>

<?php $_product = $block->getProduct(); ?>
<?php if ($_product->isSaleable()): ?>
    <v-form-item :label="i18n.qty">
        <v-qplus name="qty" v-model="qty" :change="qtyChange"></v-qplus>
    </v-form-item>
    <v-form-item>
        <v-button type="primary" native="button" v-text="i18n.buttonTitle" @click="addCart"></v-button>
        <?= $block->getChildHtml('', true) ?>
    </v-form-item>
<?php endif; ?>