<v-discount inline-template>
    <div class="in-discount">
        <h3 class="title" v-text="i18n.discountTilte"></h3>
        <div class="content">
            <v-form class="v-discount" action="<?= $block->getUrl('checkout/cart/couponPost') ?>" method="post">
                <v-form-item :label="i18n.coupon">
                    <v-input name="coupon_code" v-model="coupon"></v-input>
                </v-form-item>
                <v-form-item :classes="'in-flex'">
                    <v-button type="primary" native="button" v-text="i18n.applay"></v-button>
                    <v-button type="primary" native="button" v-text="i18n.cancelCoupon"></v-button>
                </v-form-item>
            </v-form>
        </div>
    </div>
</v-discount>