<?php
/*
* @var \Magento\Customer\Block\Form\Edit $block 
*/
?>

<v-account-edit inline-template>
    <v-form class="v-account-edit" action="<?= $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>" method="post" enctype="multipart/form-data">
        <v-form-item>
            <?= $block->getBlockHtml('formkey') ?> 
        </v-form-item>    
        <?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getCustomer())->toHtml() ?>
        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php if ($_dob->isEnabled()): ?>
            <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
        <v-form-item :classes="'in-line'">
            <v-checkbox name="change_email" v-model="changeEmail" value="1">{{i18n.changeEmail}}</v-checkbox>
            <v-checkbox name="change_password" v-model="changePassword" value="1">{{i18n.changePassword}}</v-checkbox>
        </v-form-item>
        <template v-if="changeEmail">
            <v-form-item :label="i18n.email">
                <v-input type="email" name="email" v-model="email"></v-input>
            </v-form-item>
        </template>
        <template v-if="changePassword">
            <v-form-item :label="i18n.currentPassword">
                <v-input type="password" name="current_password" :show="showEye" v-model="currentPassword"></v-input>
            </v-form-item>
            <v-form-item :label="i18n.password">
                <v-input type="password" name="password" :show="showEye" v-model="password"></v-input>
            </v-form-item>
            <v-form-item :label="i18n.comfirm">
                <v-input type="password" name="password_confirmation" :show="showEye" v-model="comfirm"></v-input>
            </v-form-item>
        </template>
        <?= $block->getChildHtml('form_additional_info') ?>
        <v-form-item>
            <v-button type="primary" native="submit" v-text="i18n.save"></v-button>
        </v-form-item>
    </v-form>
</v-account-edit>