<?php
/*
* @var \Magento\Customer\Block\Account\Forgotpassword $block 
*/
?>

<v-password inline-template>
    <v-form class="v-password" :action="password_action" method="post">
        <v-form-item>
            <p class="in-note" v-text="i18n.note"></p>
        </v-form-item>
        <v-form-item :label="i18n.email">
            <v-input type="email" name="email" v-model="email"></v-input>
        </v-form-item>
        <?= $block->getChildHtml('form_additional_info') ?>
        <v-form-item>
            <v-button type="primary" native="submit" v-text="i18n.resetPassword"></v-button>
        </v-form-item>
    </v-form>
</v-password>