<?php
/** @var \Magento\Customer\Block\Form\Login $block */
?>

<v-login-form inline-template>
    <div class="block block-customer-login">
        <div class="block-title">
            <strong v-text="i18n.title"></strong>
        </div>
        <div class="block-content">
            <form class="form form-login"
                action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
                method="post"
                data-mage-init='{"validation":{}}'>
                <?= $block->getBlockHtml('formkey') ?>
                <fieldset class="fieldset login">
                    <div class="field note" v-text="i18n.note"></div>
                    <div class="field email required">
                        <label class="label" for="email" v-text="i18n.email"></label>
                        <div class="control">
                            <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" :title="i18n.email" />
                        </div>
                    </div>
                    <div class="field password required">
                        <label for="pass" class="label" v-text="i18n.password"></label>
                        <div class="control">
                            <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" :title="i18n.password" />
                        </div>
                    </div>
                    <?= $block->getChildHtml('form_additional_info') ?>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button type="submit" class="action login primary">
                                <span v-text="i18n.signIn"></span>
                            </button>
                        </div>
                        <div class="secondary">
                            <a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>" v-text="i18n.forgot"></a>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</v-login-form>