<?php
/** @var \Magento\Customer\Block\Form\Login $block */
?>

<v-login-form inline-template>
    <div class="block block-login">
        <div class="block-title">
            <strong v-text="i18n.title"></strong>
        </div>
        <div class="block-content">
            <v-form :action="post_action" method="post">
                <v-form-item>    
                    <p class="note" v-text="i18n.note"></p>
                    <?= $block->getBlockHtml('formkey') ?>
                </v-form-item>
                <v-form-item :label="i18n.email">
                    <v-input name="login[username]" v-model="email"></v-input>
                </v-form-item>
                <v-form-item :label="i18n.password">
                    <v-input name="login[password]" v-model="password"></v-input>
                </v-form-item>
                <v-form-item :classes="'in-flex'">
                    <v-button type="primary" native="submit" v-text="i18n.signIn"></v-button>
                    <v-button type="link" :href="forgot_url" v-text="i18n.forgot"></v-button>
                </v-form-item>
            </v-form>
        </div>
    </div>
</v-login-form>