<?php
/*
* @var \Magento\Customer\Block\Newsletter $block 
*/
?>
<v-account-newsletter inline-template>
    <v-form class="form form-newsletter-manage" action="<?= $block->getAction() ?>" method="post">
        <h2 class="title" v-text="i18n.subscription"></h2>
        <?= $block->getBlockHtml('formkey') ?>
        <v-form-item>
            <v-checkbox name="is_subscribed" v-model="subscribed" value="1">{{i18n.general}}</v-checkbox>
        </v-form-item>
        <?= $block->getChildHtml('customer.form.newsletter.extra') ?>
        <v-form-item>
            <v-button type="primary" native="submit" v-text="i18n.save"></v-button>
        </v-form-item>
    </v-form>
</v-account-newsletter>