<?php
/*
* @var \Magento\Review\Block\Form $block 
*/
?>

<v-reviews inline-template>
    <div class="in-reviews">
        <h3 class="block-title" v-text="i18n.reviewTitle"></h3>
        <div class="block-content">
            <?php if ($block->getAllowWriteReviewFlag()): ?>
                <v-form action="<?= $block->getAction() ?>" class="review-form" method="post">
                    <?= $block->getChildHtml('form_fields_before') ?>
                        <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
                        <?php foreach ($block->getRatings() as $_rating): ?>
                            <v-form-item label="<?= $_rating->getRatingCode() ?>">
                                <?php $options = $_rating->getOptions();?>
                                <?php $iterator = 1; foreach ($options as $_option): ?>
                                    <v-radio name="ratings[<?= $_rating->getId() ?>]" v-model="select<?= $_rating->getRatingCode() ?>" :checked="'<?= $_option->getValue() ?>'"></v-radio>
                                <?php $iterator++; ?>
                                <?php endforeach; ?>
                            </v-form-item>
                        <?php endforeach; ?>
                        <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                    <?php endif ?>
                    <v-form-item :label="i18n.nickname">
                        <v-input name="nickname" v-model="nickname"></v-input>
                    </v-form-item>
                    <v-form-item :label="i18n.summary">
                        <v-input name="title" v-model="summary"></v-input>
                    </v-form-item>
                    <v-form-item :label="i18n.detail">
                        <v-textarea name="detail" :auto="auto" v-model="detail"></v-textarea>
                    </v-form-item>
                    <v-form-item>
                        <v-button type="primary" native="button" v-text="i18n.submitReview"></v-button>
                    </v-form-item>
                </v-form>
            <?php else: ?>
                <div class="message info notlogged" v-html="notLogin"></div>
            <?php endif ?>
        </div>
    </div>
</v-reviews>