query getProducts ($id: Int!) {
    category(id: $id) {
        products {
            total_count
            page_info {
                current_page
                page_size
            }
        }
        children_count
        children {
            id
            level
            name
            path
            children {
                id
                level
                name
                path
                children {
                    id
                    level
                    name
                    path
                    children {
                        id
                        level
                        name
                        path
                    }
                }
            }
        }
    }
}