<?php
/*
* @var \Magento\Review\Block\Product\ReviewRenderer $block 
*/

$url = $block->getReviewsUrl();
?>

<?php if ($block->getReviewsCount()): ?>
    <?php $rating = $block->getRatingSummary(); ?>
    <div class="product-reviews-summary<?= !$rating ? ' no-rating' : '' ?>">
        <?php if ($rating):?>
        <div class="rating-summary">
            <div class="rating-result" title="<?= $block->escapeHtmlAttr($rating); ?>%">
                <span style="width:<?= $block->escapeHtmlAttr($rating); ?>%">
                    <span>
                        <span itemprop="ratingValue"><?= $block->escapeHtml($rating); ?></span>% of <span itemprop="bestRating">100</span>
                    </span>
                </span>
            </div>
        </div>
        <?php endif;?>
        <div class="reviews-actions">
            <a class="action view"
            href="<?= $block->escapeUrl($url) ?>">
                <span itemprop="reviewCount"><?= $block->escapeHtml($block->getReviewsCount()) ?></span>
                <span><?= ($block->getReviewsCount() == 1) ? $block->escapeHtml(__('Review')) : $block->escapeHtml(__('Reviews')) ?></span>
            </a>
            <a class="action add" href="<?= $block->escapeUrl($url) ?>"><?= $block->escapeHtml(__('Add Review')) ?></a>
        </div>
    </div>
<?php elseif ($block->getDisplayIfEmpty()): ?>
    <div class="product-reviews-summary empty">
        <div class="reviews-actions">
            <a class="action add" href="<?= $block->escapeUrl($url) ?>">
                <?= $block->escapeHtml(__('The first to review')) ?>
            </a>
        </div>
    </div>
<?php endif; ?>