<?php
/*
* @var \Magento\Customer\Block\Widget\Dob $block 
*/
?>

<v-form-item :label="'<?= $block->getLabel() ?>'">
    <v-datepicker name="<?= $block->getHtmlId() ?>" type="ymdHms" v-model="<?= $block->getHtmlId() ?>"></v-datepicker>
    <?php if ($_message = $block->getAdditionalDescription()) : ?>
        <div class="note"><?= $block->escapeHtml($_message) ?></div>
    <?php endif; ?>
</v-form-item>