mutation changePassword($currentPassword: String!, $newPassword: String!) {
    changeCustomerPassword(currentPassword: $currentPassword, newPassword: $newPassword) {
        created_at
        default_billing
        default_shipping
        dob
        email
        firstname
        gender
        group_id
        id
        is_subscribed
        lastname
        middlename
        prefix
        suffix
        taxvat
    }
}