query getCmsBlock($identifiers: [String], $onServer: Boolean!) {
    cmsBlocks(identifiers: $identifiers) {
        items {
            identifier
            title
            content
        }
    }
}