<?php
/*
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>

<div class="in-sorter">
    <p class="label"><?= __('Sort By') ?></p>
    <select class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <option value="<?= $_key ?>"
                <?php if ($block->isOrderCurrent($_key)): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?= __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc">
            <span><?= __('Set Ascending Direction') ?></span>
        </a>
    <?php else: ?>
        <a title="<?= __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc">
            <span><?= __('Set Descending Direction') ?></span>
        </a>
    <?php endif; ?>
</div>