<?php
/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
    <v-login-customer inline-template>
        <div class="block block-customer">
            <div class="block-title">
                <strong v-text="i18n.createTitle"></strong>
            </div>
            <div class="block-content">
                <p v-text="i18n.createMsg"></p>
                <v-button type="primary" :href="create_url" v-text="i18n.createButton"></v-button>
            </div>
        </div>
    </v-login-customer>
<?php endif; ?>