query getProducts ($id: Int!, $pageSize: Int!, $currentPage: Int!, $onServer: Boolean!) {
    category(id: $id) {
        id
        name
        display_mode
        filter_price_range
        default_sort_by
        available_sort_by
        children {
            id
            name
            url_key
            url_path
        }
        products(pageSize: $pageSize, currentPage: $currentPage, sort: {

        }) {
            items {
                id
                name
                sku
                type_id
                image {
                    label
                    url
                }
                price {
                    regularPrice {
                        amount {
                            currency
                            value        
                        }
                    }
                }
                swatch_image
                special_price
                tier_price
                stock_status
                url_key
                url_path
                new_from_date
                new_to_date
                special_from_date
                special_to_date
                only_x_left_in_stock
                short_description {
                    html
                }
                created_at
                updated_at
            }
            page_info {
                current_page
                page_size
            }
            total_count
        }
        meta_description @include(if: $onServer)
        meta_keywords @include(if: $onServer)
        meta_title @include(if: $onServer)
        created_at
        updated_at
    }
}