<?php
/*
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>

<div class="in-sorter">
    <v-form-item :label="i18n.sortby">
        <v-select :placeholder="i18n.chooseSorter" :options="sorter" v-model="selectSorter" :filterable=true :number=8 @change="changeSorter"></v-select>
    </v-form-item>
    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?= __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc">
            <span><?= __('Set Ascending Direction') ?></span>
        </a>
    <?php else: ?>
        <a title="<?= __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc">
            <span><?= __('Set Descending Direction') ?></span>
        </a>
    <?php endif; ?>
</div>